# Generated by Django 4.2.5 on 2023-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='image_height',
            field=models.PositiveIntegerField(help_text='Высота загруженного изображения', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_wigth',
            field=models.PositiveIntegerField(help_text='Ширина загруженного изображения', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='profile/', width_field='image_width'),
        ),
    ]
