# Generated by Django 4.2.5 on 2023-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options_profile_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, help_text='Высота загруженного изображения', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_wigth',
            field=models.PositiveIntegerField(blank=True, help_text='Ширина загруженного изображения', null=True),
        ),
    ]
