# Generated by Django 4.2.5 on 2023-10-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image_height_alter_profile_image_wigth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image_wigth',
            new_name='image_width',
        ),
    ]
