# Generated by Django 4.2.6 on 2023-10-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=3, verbose_name='Буква класса')),
                ('number', models.PositiveIntegerField(verbose_name='Номер класса')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.curator', verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
    ]
