# Generated by Django 4.2.6 on 2023-10-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zauch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zauch',
            name='image',
            field=models.ImageField(upload_to='Zauchi/', verbose_name='Изображение'),
        ),
    ]
