# Generated by Django 4.2.6 on 2023-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Директор', 'verbose_name_plural': 'Директора'},
        ),
        migrations.AlterField(
            model_name='director',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='Телефон'),
        ),
    ]
